In [391]:
import sys
import tkinter
import tkinter.messagebox
from tkintermapview import TkinterMapView
from pyswip import Prolog
import pandas as pd
import re

In [392]:
df = pd.read_csv('Destinations.csv')

country = pd.DataFrame(df, columns=["Destinations", "country"])
region = pd.DataFrame(df, columns=["Destinations", "region"])
climate = pd.DataFrame(df, columns=["Destinations", "Climate"])
budget = pd.DataFrame(df, columns=["Destinations", "Budget"])
activity = pd.DataFrame(df, columns=["Destinations", "Activity"])
demographics = pd.DataFrame(df, columns=["Destinations", "Demographics"])
duration = pd.DataFrame(df, columns=["Destinations", "Duration"])
cuisine = pd.DataFrame(df, columns=["Destinations", "Cuisine"])
history = pd.DataFrame(df, columns=["Destinations", "History"])
natural_wonder = pd.DataFrame(df, columns=["Destinations", "Natural Wonder"])
accommodation = pd.DataFrame(df, columns=["Destinations", "Accommodation"])
language = pd.DataFrame(df, columns=["Destinations", "Language"])

In [393]:
prolog = Prolog()

prolog.retractall("country(_,_)")
prolog.retractall("region(_,_)")
prolog.retractall("climate(_,_)")
prolog.retractall("budget(_,_)")
prolog.retractall("activity(_,_)")
prolog.retractall("demographics(_,_)")
prolog.retractall("duration(_,_)")
prolog.retractall("cuisine(_,_)")
prolog.retractall("history(_,_)")
prolog.retractall("natural_wonder(_,_)")
prolog.retractall("accommodation(_,_)")
prolog.retractall("language(_,_)")

In [394]:
def dfToStr (df, interpretation):
    prefix =  interpretation + "("
    suffix = ")"
    final_str_list = []
    for i in range (df.shape[0]):
        a = []
        a = df.loc[i].tolist()
        
        if "," in a[1]:
            splited_list = a[1].split(", ")
            a[0] = chr(34) + a[0] + chr(34)
            for j in splited_list:
                row_values_str = a[0].lower().replace(" ", "_") + ', ' + j.lower().replace(" ", "_")
                finalStr = prefix + row_values_str + suffix
                final_str_list.append(finalStr)
            
        else:
            a[0] = chr(34) + a[0] + chr(34)
            row_values_str = a[0].lower().replace(" ", "_") + ', ' + a[1].lower().replace(" ", "_")
            finalStr = prefix + row_values_str + suffix
            final_str_list.append(finalStr)
        
    return final_str_list

In [395]:
dfToStr(country, "country")

['country("tokyo", japan)',
 'country("ottawa", canada)',
 'country("mexico_city", mexico)',
 'country("rome", italy)',
 'country("brasilia", brazil)',
 'country("canberra", australia)',
 'country("new_delhi", india)',
 'country("pretoria", south_africa)',
 'country("madrid", spain)',
 'country("moscow", russia)',
 'country("berlin", germany)',
 'country("bangkok", thailand)',
 'country("stockholm", sweden)',
 'country("cairo", egypt)',
 'country("wellington", new_zealand)',
 'country("ankara", turkey)',
 'country("buenos_aires", argentina)',
 'country("kathmandu", nepal)',
 'country("athens", greece)',
 'country("nairobi", kenya)',
 'country("lisbon", portugal)',
 'country("oslo", norway)',
 'country("jakarta", indonesia)',
 'country("hanoi", vietnam)',
 'country("dublin", ireland)',
 'country("beijing", china)',
 'country("paris", france)',
 'country("santiago", chile)',
 'country("rabat", morocco)',
 'country("singapore", singapore)',
 'country("lima", peru)',
 'country("helsinki", finland)',
 'country("prague", czech_republic)',
 'country("manila", philippines)',
 'country("brussels", belgium)',
 'country("kuala_lumpur", malaysia)',
 'country("amsterdam", netherlands)',
 'country("washington_d.c.", united_states)',
 'country("london", united_kingdom)',
 'country("seoul", south_korea)',
 'country("bogota", colombia)',
 'country("warsaw", poland)',
 'country("jerusalem", israel)',
 'country("kyiv", ukraine)',
 'country("vienna", austria)',
 'country("copenhagen", denmark)',
 'country("dhaka", bangladesh)',
 'country("montevideo", uruguay)',
 'country("bern", switzerland)',
 'country("islamabad", pakistan)',
 'country("budapest", hungary)',
 'country("zagreb", croatia)',
 'country("colombo", sri_lanka)',
 'country("tehran", iran)',
 'country("bratislava", slovakia)',
 'country("cancun", mexico)',
 'country("venice", italy)',
 'country("florence", italy)',
 'country("milan", italy)',
 'country("saint_petersburg", russia)',
 'country("vladivostok", russia)',
 'country("new_york_city", united_states)',
 'country("los_angeles", united_states)',
 'country("chicago", united_states)',
 'country("miami", united_states)',
 'country("shiraz", iran)',
 'country("isfahan", iran)',
 'country("mashhad", iran)',
 'country("tabriz", iran)',
 'country("yazd", iran)',
 'country("shanghai", china)',
 'country("guangzhou", china)',
 'country("chengdu", china)',
 'country("xi\'an", china)',
 'country("bergen", norway)',
 'country("troms√∏", norway)',
 'country("marseille", france)',
 'country("lyon", france)',
 'country("sentosa", singapore)',
 'country("marina_bay", singapore)',
 'country("cusco", peru)',
 'country("arequipa", peru)',
 'country("busan", south_korea)',
 'country("incheon", south_korea)',
 'country("medellin", colombia)',
 'country("cali", colombia)',
 'country("lahore", pakistan)',
 'country("karachi", pakistan)',
 'country("zurich", switzerland)',
 'country("geneva", switzerland)',
 'country("izmir", turkey)',
 'country("antalya", turkey)',
 'country("bursa", turkey)',
 'country("munich", germany)',
 'country("hamburg", germany)',
 'country("frankfurt", germany)',
 'country("alexandria", egypt)',
 'country("luxor", egypt)',
 'country("aswan", egypt)',
 'country("christchurch", new_zealand)',
 'country("queenstown", new_zealand)',
 'country("rotorua", new_zealand)']

In [396]:
def add_kb(syntax_list):
    for i in range(len(syntax_list)):
        prolog.assertz(syntax_list[i])

In [397]:
add_kb(dfToStr(country, "country"))
add_kb(dfToStr(region, "region"))
add_kb(dfToStr(climate, "climate"))
add_kb(dfToStr(activity, "activity"))
add_kb(dfToStr(demographics, "demographics"))
add_kb(dfToStr(budget, "budget"))
add_kb(dfToStr(duration, "duration"))
add_kb(dfToStr(cuisine, "cuisine"))
add_kb(dfToStr(history, "history"))
add_kb(dfToStr(natural_wonder, "natural_wonder"))
add_kb(dfToStr(accommodation, "accommodation"))
add_kb(dfToStr(language, "language"))

In [398]:
query = "language(City, german)"
results = list(prolog.query(query))
for result in results:
    print(result["City"])

b'berlin'
b'brussels'
b'vienna'
b'bern'
b'zurich'
b'munich'
b'hamburg'
b'frankfurt'

In [399]:
df

,Destinations,country,region,Climate,Budget,Activity,Demographics,Duration,Cuisine,History,Natural Wonder,Accommodation,Language
0,Tokyo,Japan,East Asia,Temperate,High,Cultural,Solo,Long,Asian,Modern,Mountains,Luxury,Japanese
1,Ottawa,Canada,North America,Cold,Medium,Adventure,Family-friendly,Medium,European,Modern,Forests,Mid-range,English
2,Mexico City,Mexico,North America,Temperate,Low,Cultural,Senior,Short,Latin American,Ancient,Mountains,Budget,Spanish
3,Rome,Italy,Southern Europe,Temperate,High,Cultural,Solo,Medium,European,Ancient,Beaches,Luxury,Italian
4,Brasilia,Brazil,South America,Tropical,Low,Adventure,Family-friendly,Long,Latin American,Modern,Beaches,Budget,Portuguese
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Luxor,Egypt,North Africa,Desert,Low,Cultural,Solo,Short,Middle Eastern,Ancient,Rivers,Budget,Arabic
98,Aswan,Egypt,North Africa,Desert,Low,Cultural,Solo,Short,Middle Eastern,Ancient,Rivers,Budget,Arabic
99,Christchurch,New Zealand,Oceania,Temperate,Medium,Adventure,Family-friendly,Medium,Western,Modern,Cityscape,Mid-range,English
100,Queenstown,New Zealand,Oceania,Temperate,High,Adventure,Solo,Short,Western,Modern,Mountains,Luxury,English
101,Rotorua,New Zealand,Oceania,Temperate,Medium,Cultural,Family-friendly,Short,Western,Modern,Geothermal,Mid-range,English

In [400]:
country_set = set(df['country'].tolist())
region_set = set(df['region'].tolist())
climate_set = set(df['Climate'].tolist())
budget_set = set(df['Budget'].tolist())
activity_set = set(df['Activity'].tolist())
demographics_set = set(df['Demographics'].tolist())
duration_set = set(df['Duration'].tolist())
cuisine_set = set(df['Cuisine'].tolist())
history_set = set(df['History'].tolist())
natural_wonder_set = set(df['Natural Wonder'].tolist())
accommodation_set = set(df['Accommodation'].tolist())
language_set = set(df['Language'].tolist())

In [401]:
def create_dict(key_label,value_list):
    value_list = [word.lower().replace(" ", "_") for word in value_list]
    keyword_dict.update({key_label: value_list})

In [402]:
country_list = list(country_set)
region_list = list(region_set)
climate_list = list(climate_set)
budget_list = list(budget_set)
activity_list = list(activity_set)
demographics_list = list(demographics_set)
duration_list = list(duration_set)
cuisine_list = list(cuisine_set)
history_list = list(history_set)
natural_wonder_list = list(natural_wonder_set)
accommodation_list = list(accommodation_set)
language_list = list(language_set)

keyword_dict = {}
create_dict('country', country_list)
create_dict('region', region_list)
create_dict('climate', climate_list)
create_dict('budget', budget_list)
create_dict('activity', activity_list)
create_dict('demographics', demographics_list)
create_dict('duration', duration_list)
create_dict('cuisine', cuisine_list)
create_dict('history', history_list)
create_dict('natural_wonder', natural_wonder_list)
create_dict('accommodation', accommodation_list)
create_dict('language', language_list)

In [403]:
print(keyword_dict)

{'country': ['australia', 'sri_lanka', 'united_states', 'argentina', 'slovakia', 'ukraine', 'united_kingdom', 'germany', 'sweden', 'kenya', 'colombia', 'russia', 'uruguay', 'new_zealand', 'singapore', 'vietnam', 'spain', 'malaysia', 'croatia', 'chile', 'ireland', 'iran', 'finland', 'greece', 'south_korea', 'mexico', 'pakistan', 'austria', 'czech_republic', 'italy', 'canada', 'japan', 'peru', 'bangladesh', 'belgium', 'denmark', 'morocco', 'hungary', 'switzerland', 'thailand', 'china', 'philippines', 'poland', 'israel', 'south_africa', 'nepal', 'brazil', 'portugal', 'turkey', 'norway', 'indonesia', 'egypt', 'netherlands', 'france', 'india'], 'region': ['northern_europe', 'eurasia', 'north_america', 'africa', 'eastern_europe', 'southeast_asia', 'middle_east', 'oceania', 'southern_europe', 'south_america', 'western_europe', 'east_asia', 'north_africa', 'south_asia'], 'climate': ['varied', 'temperate', 'cold', 'mediterranean', 'tropical', 'desert'], 'budget': ['low', 'high', 'medium'], 'activity': ['cultural', 'business', 'adventure'], 'demographics': ['business', 'family-friendly', 'couples', 'solo', 'senior'], 'duration': ['short', 'medium', 'long'], 'cuisine': ['eastern_european', 'asian', 'african', 'western', 'european', 'middle_eastern', 'latin_american'], 'history': ['medieval', 'ancient', 'modern'], 'natural_wonder': ['lakes', 'geothermal', 'deserts', 'mountains', 'rivers', 'beaches', 'fjords', 'desert', 'northern_lights', 'volcanoes', 'cityscape', 'forests'], 'accommodation': ['budget', 'mid-range', 'luxury'], 'language': ['persian', 'dutch,_french,_german', 'danish', 'croatian', 'english', 'russian', 'malay', 'polish', 'french', 'swahili', 'swedish', 'german,_french,_italian', 'indonesian', 'spanish', 'english,_spanish', 'german', 'arabic', 'czech', 'urdu', 'nepali', 'finnish', 'thai', 'hindi', 'hebrew', 'norwegian', 'turkish', 'hungarian', 'dutch', 'vietnamese', 'japanese', 'sinhala,_tamil', 'italian', 'korean', 'slovak', 'ukrainian', 'filipino', 'mandarin', 'portuguese', 'greek', 'bengali']}

In [406]:
def extract_keywords(text, keyword_dict):
    text = re.sub(r'[^a-zA-Z_ ]', '', text)
    words = text.split()
    print(words)

    extracted_keywords = []

    for word in words:
        for key, value in keyword_dict.items():
            if word in value:
                extracted_keywords.append(word)

    return extracted_keywords

user_text = "I would like to travel somewhere in south_america activity with low."

result_keywords = extract_keywords(user_text, keyword_dict)

print(result_keywords)

['I', 'would', 'like', 'to', 'travel', 'somewhere', 'in', 'south_america', 'activity', 'with', 'low']
['south_america', 'low']

In [407]:
def send_query(extracted_keywords):
    i = 0
    results = []
    for word in extracted_keywords:
        for key, value in keyword_dict.items():
            if word in value:
                if i == 0:
                    query = f"{key}(City, {word})"
                    temp = list(prolog.query(query))
                    results = temp
                else:
                    query = f"{key}(City, {word})"
                    results = list(prolog.query(query))
        temp = [value for value in results if value in temp]
        i += 1
    for result in temp:
        print(result["City"])

In [408]:
send_query(result_keywords)

b'brasilia'
b'buenos_aires'
b'lima'
b'bogota'
b'cusco'
b'arequipa'
b'medellin'
b'cali'