In [86]:
import sys
import tkinter
import tkinter.messagebox
from tkintermapview import TkinterMapView
from pyswip import Prolog
import pandas as pd
import re

In [87]:
df = pd.read_csv('Destinations.csv')
df_graph = pd.read_csv('Bi_Adjacency_matrix.csv')

country = pd.DataFrame(df, columns=["Destinations", "country"])
region = pd.DataFrame(df, columns=["Destinations", "region"])
climate = pd.DataFrame(df, columns=["Destinations", "Climate"])
budget = pd.DataFrame(df, columns=["Destinations", "Budget"])
activity = pd.DataFrame(df, columns=["Destinations", "Activity"])
demographics = pd.DataFrame(df, columns=["Destinations", "Demographics"])
duration = pd.DataFrame(df, columns=["Destinations", "Duration"])
cuisine = pd.DataFrame(df, columns=["Destinations", "Cuisine"])
history = pd.DataFrame(df, columns=["Destinations", "History"])
natural_wonder = pd.DataFrame(df, columns=["Destinations", "Natural Wonder"])
accommodation = pd.DataFrame(df, columns=["Destinations", "Accommodation"])
language = pd.DataFrame(df, columns=["Destinations", "Language"])

In [88]:
prolog = Prolog()

prolog.retractall("country(_,_)")
prolog.retractall("region(_,_)")
prolog.retractall("climate(_,_)")
prolog.retractall("budget(_,_)")
prolog.retractall("activity(_,_)")
prolog.retractall("demographics(_,_)")
prolog.retractall("duration(_,_)")
prolog.retractall("cuisine(_,_)")
prolog.retractall("history(_,_)")
prolog.retractall("natural_wonder(_,_)")
prolog.retractall("accommodation(_,_)")
prolog.retractall("language(_,_)")

In [89]:
def dfToStr (df, interpretation):
    prefix =  interpretation + "("
    suffix = ")"
    final_str_list = []
    for i in range (df.shape[0]):
        a = []
        a = df.loc[i].tolist()
        
        if "," in a[1]:
            splited_list = a[1].split(", ")
            a[0] = chr(39) + a[0] + chr(39)
            for j in splited_list:
                row_values_str = a[0].lower().replace(" ", "_") + ', ' + j.lower().replace(" ", "_")
                row_values_str = row_values_str.replace(".", "")
                row_values_str = row_values_str.replace("'", "")
                finalStr = prefix + row_values_str + suffix
                final_str_list.append(finalStr)
            
        else:
            a[0] = chr(39) + a[0] + chr(39)
            row_values_str = a[0].lower().replace(" ", "_") + ', ' + a[1].lower().replace(" ", "_")
            row_values_str = row_values_str.replace(".", "")
            row_values_str = row_values_str.replace("'", "")
            finalStr = prefix + row_values_str + suffix
            final_str_list.append(finalStr)
        
    return final_str_list

In [90]:
dfToStr(country, "country")

['country(tokyo, japan)',
 'country(ottawa, canada)',
 'country(mexico_city, mexico)',
 'country(rome, italy)',
 'country(brasilia, brazil)',
 'country(canberra, australia)',
 'country(new_delhi, india)',
 'country(pretoria, south_africa)',
 'country(madrid, spain)',
 'country(moscow, russia)',
 'country(berlin, germany)',
 'country(bangkok, thailand)',
 'country(stockholm, sweden)',
 'country(cairo, egypt)',
 'country(wellington, new_zealand)',
 'country(ankara, turkey)',
 'country(buenos_aires, argentina)',
 'country(kathmandu, nepal)',
 'country(athens, greece)',
 'country(nairobi, kenya)',
 'country(lisbon, portugal)',
 'country(oslo, norway)',
 'country(jakarta, indonesia)',
 'country(hanoi, vietnam)',
 'country(dublin, ireland)',
 'country(beijing, china)',
 'country(paris, france)',
 'country(santiago, chile)',
 'country(rabat, morocco)',
 'country(singapore, singapore)',
 'country(lima, peru)',
 'country(helsinki, finland)',
 'country(prague, czech_republic)',
 'country(manila, philippines)',
 'country(brussels, belgium)',
 'country(kuala_lumpur, malaysia)',
 'country(amsterdam, netherlands)',
 'country(washington_dc, united_states)',
 'country(london, united_kingdom)',
 'country(seoul, south_korea)',
 'country(bogota, colombia)',
 'country(warsaw, poland)',
 'country(jerusalem, israel)',
 'country(kyiv, ukraine)',
 'country(vienna, austria)',
 'country(copenhagen, denmark)',
 'country(dhaka, bangladesh)',
 'country(montevideo, uruguay)',
 'country(bern, switzerland)',
 'country(islamabad, pakistan)',
 'country(budapest, hungary)',
 'country(zagreb, croatia)',
 'country(colombo, sri_lanka)',
 'country(tehran, iran)',
 'country(bratislava, slovakia)',
 'country(cancun, mexico)',
 'country(venice, italy)',
 'country(florence, italy)',
 'country(milan, italy)',
 'country(saint_petersburg, russia)',
 'country(vladivostok, russia)',
 'country(new_york_city, united_states)',
 'country(los_angeles, united_states)',
 'country(chicago, united_states)',
 'country(miami, united_states)',
 'country(shiraz, iran)',
 'country(isfahan, iran)',
 'country(mashhad, iran)',
 'country(tabriz, iran)',
 'country(yazd, iran)',
 'country(shanghai, china)',
 'country(guangzhou, china)',
 'country(chengdu, china)',
 'country(xian, china)',
 'country(bergen, norway)',
 'country(troms√∏, norway)',
 'country(marseille, france)',
 'country(lyon, france)',
 'country(sentosa, singapore)',
 'country(marina_bay, singapore)',
 'country(cusco, peru)',
 'country(arequipa, peru)',
 'country(busan, south_korea)',
 'country(incheon, south_korea)',
 'country(medellin, colombia)',
 'country(cali, colombia)',
 'country(lahore, pakistan)',
 'country(karachi, pakistan)',
 'country(zurich, switzerland)',
 'country(geneva, switzerland)',
 'country(izmir, turkey)',
 'country(antalya, turkey)',
 'country(bursa, turkey)',
 'country(munich, germany)',
 'country(hamburg, germany)',
 'country(frankfurt, germany)',
 'country(alexandria, egypt)',
 'country(luxor, egypt)',
 'country(aswan, egypt)',
 'country(christchurch, new_zealand)',
 'country(queenstown, new_zealand)',
 'country(rotorua, new_zealand)']

In [91]:
def add_kb(syntax_list):
    for i in range(len(syntax_list)):
        prolog.assertz(syntax_list[i])

In [92]:
add_kb(dfToStr(country, "country"))
add_kb(dfToStr(region, "region"))
add_kb(dfToStr(climate, "climate"))
add_kb(dfToStr(activity, "activity"))
add_kb(dfToStr(demographics, "demographics"))
add_kb(dfToStr(budget, "budget"))
add_kb(dfToStr(duration, "duration"))
add_kb(dfToStr(cuisine, "cuisine"))
add_kb(dfToStr(history, "history"))
add_kb(dfToStr(natural_wonder, "natural_wonder"))
add_kb(dfToStr(accommodation, "accommodation"))
add_kb(dfToStr(language, "language"))

In [93]:
query = "language(City, german)"
results = list(prolog.query(query))
for result in results:
    print(result["City"])

berlin
brussels
vienna
bern
zurich
munich
hamburg
frankfurt

In [94]:
df

,Destinations,country,region,Climate,Budget,Activity,Demographics,Duration,Cuisine,History,Natural Wonder,Accommodation,Language
0,Tokyo,Japan,East Asia,Temperate,High,Cultural,Solo,Long,Asian,Modern,Mountains,Luxury,Japanese
1,Ottawa,Canada,North America,Cold,Medium,Adventure,Family-friendly,Moderate,European,Modern,Forests,Mid-range,English
2,Mexico City,Mexico,North America,Temperate,Low,Cultural,Senior,Short,Latin American,Ancient,Mountains,Budget,Spanish
3,Rome,Italy,Southern Europe,Temperate,High,Cultural,Solo,Moderate,European,Ancient,Beaches,Luxury,Italian
4,Brasilia,Brazil,South America,Tropical,Low,Adventure,Family-friendly,Long,Latin American,Modern,Beaches,Budget,Portuguese
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Luxor,Egypt,North Africa,Arid,Low,Cultural,Solo,Short,Middle Eastern,Ancient,Rivers,Budget,Arabic
98,Aswan,Egypt,North Africa,Arid,Low,Cultural,Solo,Short,Middle Eastern,Ancient,Rivers,Budget,Arabic
99,Christchurch,New Zealand,Oceania,Temperate,Medium,Adventure,Family-friendly,Moderate,Western,Modern,Cityscape,Mid-range,English
100,Queenstown,New Zealand,Oceania,Temperate,High,Adventure,Solo,Short,Western,Modern,Mountains,Luxury,English
101,Rotorua,New Zealand,Oceania,Temperate,Medium,Cultural,Family-friendly,Short,Western,Modern,Geothermal,Mid-range,English

In [95]:
country_set = set(df['country'].tolist())
region_set = set(df['region'].tolist())
climate_set = set(df['Climate'].tolist())
budget_set = set(df['Budget'].tolist())
activity_set = set(df['Activity'].tolist())
demographics_set = set(df['Demographics'].tolist())
duration_set = set(df['Duration'].tolist())
cuisine_set = set(df['Cuisine'].tolist())
history_set = set(df['History'].tolist())
natural_wonder_set = set(df['Natural Wonder'].tolist())
accommodation_set = set(df['Accommodation'].tolist())
language_set = set(df['Language'].tolist())

In [96]:
def create_dict(key_label,value_list):
    value_list = [word.lower().replace(" ", "_") for word in value_list]
    keyword_dict.update({key_label: value_list})

In [97]:
country_list = list(country_set)
region_list = list(region_set)
climate_list = list(climate_set)
budget_list = list(budget_set)
activity_list = list(activity_set)
demographics_list = list(demographics_set)
duration_list = list(duration_set)
cuisine_list = list(cuisine_set)
history_list = list(history_set)
natural_wonder_list = list(natural_wonder_set)
accommodation_list = list(accommodation_set)
language_list = list(language_set)

keyword_dict = {}
create_dict('country', country_list)
create_dict('region', region_list)
create_dict('climate', climate_list)
create_dict('budget', budget_list)
create_dict('activity', activity_list)
create_dict('demographics', demographics_list)
create_dict('duration', duration_list)
create_dict('cuisine', cuisine_list)
create_dict('history', history_list)
create_dict('natural_wonder', natural_wonder_list)
create_dict('accommodation', accommodation_list)
create_dict('language', language_list)

In [98]:
print(keyword_dict)

{'country': ['egypt', 'israel', 'ukraine', 'philippines', 'denmark', 'greece', 'vietnam', 'italy', 'indonesia', 'bangladesh', 'uruguay', 'ireland', 'india', 'norway', 'austria', 'russia', 'slovakia', 'netherlands', 'chile', 'united_kingdom', 'sweden', 'new_zealand', 'spain', 'morocco', 'singapore', 'portugal', 'nepal', 'belgium', 'poland', 'united_states', 'pakistan', 'thailand', 'canada', 'malaysia', 'germany', 'australia', 'south_africa', 'argentina', 'turkey', 'kenya', 'china', 'iran', 'croatia', 'hungary', 'colombia', 'switzerland', 'japan', 'sri_lanka', 'south_korea', 'peru', 'france', 'finland', 'czech_republic', 'brazil', 'mexico'], 'region': ['africa', 'southeast_asia', 'oceania', 'northern_europe', 'south_america', 'southern_europe', 'western_europe', 'middle_east', 'north_america', 'south_asia', 'eastern_europe', 'eurasia', 'north_africa', 'east_asia'], 'climate': ['varied', 'mediterranean', 'tropical', 'cold', 'temperate', 'arid'], 'budget': ['low', 'medium', 'high'], 'activity': ['adventure', 'business', 'cultural'], 'demographics': ['couples', 'business', 'senior', 'solo', 'family-friendly'], 'duration': ['short', 'long', 'moderate'], 'cuisine': ['middle_eastern', 'african', 'latin_american', 'european', 'eastern_european', 'asian', 'western'], 'history': ['ancient', 'modern', 'medieval'], 'natural_wonder': ['forests', 'northern_lights', 'mountains', 'fjords', 'cityscape', 'geothermal', 'deserts', 'rivers', 'beaches', 'lakes', 'volcanoes'], 'accommodation': ['budget', 'mid-range', 'luxury'], 'language': ['persian', 'slovak', 'japanese', 'turkish', 'urdu', 'greek', 'german', 'spanish', 'polish', 'german,_french,_italian', 'english,_spanish', 'sinhala,_tamil', 'english', 'bengali', 'ukrainian', 'arabic', 'malay', 'czech', 'danish', 'dutch,_french,_german', 'french', 'hindi', 'swedish', 'russian', 'indonesian', 'hungarian', 'mandarin', 'nepali', 'portuguese', 'swahili', 'vietnamese', 'norwegian', 'filipino', 'korean', 'dutch', 'italian', 'thai', 'croatian', 'hebrew', 'finnish']}

In [99]:
def extract_keywords(text, keyword_dict):
    text = re.sub(r'[^a-zA-Z_ ]', '', text).lower()
    words = text.split()

    extracted_keywords = []

    for word in words:
        for key, value in keyword_dict.items():
            if word in value:
                extracted_keywords.append(word)

    return extracted_keywords

user_text = "As a solo traveler with a passion for ancient cultures, I'm eager to immerse myself in the rich heritage of the Persian language. My journey is not just about sightseeing but delving deep into the linguistic roots of one of the world's oldest languages. Traveling alone will allow me the freedom to explore at my own pace, meet local speakers, and gain a firsthand understanding of the nuances of Persian in its native setting."

result_keywords = extract_keywords(user_text, keyword_dict)

print(result_keywords)

['solo', 'ancient', 'persian', 'persian']

In [100]:
def send_query(extracted_keywords):
    i = 0
    results = []
    for word in extracted_keywords:
        for key, value in keyword_dict.items():
            if word in value:
                if i == 0:
                    query = f"{key}(City, {word})"
                    temp = list(prolog.query(query))
                    results = temp
                else:
                    query = f"{key}(City, {word})"
                    results = list(prolog.query(query))
        temp = [value for value in results if value in temp]
        i += 1
    for result in temp:
        print(result["City"])

In [101]:
send_query(result_keywords)

tehran
shiraz
mashhad
tabriz
yazd

In [102]:
df_graph

,Destinations,Tokyo,Ottawa,Mexico City,Rome,Brasilia,Canberra,New Delhi,Pretoria,Madrid,...,Bursa,Munich,Hamburg,Frankfurt,Alexandria,Luxor,Aswan,Christchurch,Queenstown,Rotorua
0,Tokyo,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Ottawa,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
2,Mexico City,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Rome,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Brasilia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Luxor,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,Aswan,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
99,Christchurch,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100,Queenstown,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101,Rotorua,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [103]:
prolog.retractall("directly_connected(_,_)")
prolog.retractall("connected(_,_)")

In [104]:
def connection_city(df):
    connections_dict = {}
    destinations_dict = dict(df['Destinations']) 
    for i in range(df_graph.shape[0]):
        connected_cities = []
        df_graph_row = df_graph.loc[i].tolist()
        del df_graph_row[0]
        for j in range(len(df_graph_row)):
            if df_graph_row[j] == 1:
                connected_cities.append(destinations_dict[j])
                
        result = one_way(connected_cities, destinations_dict[i])
        connections_dict.update({destinations_dict[i]: connected_cities})

    return connections_dict

In [105]:
connections_dict = connection_city(df_graph)

In [106]:
def one_way(connected_cities, city):
    prefix =  "directly_connected" + "("
    suffix = ")"
    final_str_list = []
    for i in range (len(connected_cities)):
        row_values_str =city.lower().replace(" ", "_") + ', ' + connected_cities[i].lower().replace(" ", "_")
        row_values_str = row_values_str.replace(".", "")
        row_values_str = row_values_str.replace("'", "")
        finalStr = prefix + row_values_str + suffix
        final_str_list.append(finalStr)
    return final_str_list

In [107]:
query = "directly_connected(City, rome)"
results = list(prolog.query(query))
for result in results:
    print(result["City"])

In [108]:
connections_dict

{'Tokyo': ['Bogota', 'Miami', 'Lahore'],
 'Ottawa': ['Dublin', 'Amsterdam', 'Zagreb', 'Bursa', 'Munich'],
 'Mexico City': ['Milan',
  'New York City',
  'Shiraz',
  'Chengdu',
  'Bergen',
  'Lahore'],
 'Rome': ['Lisbon', 'Washington D.C.', 'London', 'Chicago', 'Yazd'],
 'Brasilia': ['Cairo', 'Ankara', 'Beijing', 'Izmir'],
 'Canberra': ['Wellington',
  'Rabat',
  'Washington D.C.',
  'Montevideo',
  'Florence',
  'Los Angeles',
  'Shanghai',
  'Chengdu',
  'Karachi',
  'Luxor'],
 'New Delhi': ['Wellington',
  'Athens',
  'Santiago',
  'Singapore',
  'Isfahan',
  'Troms√∏',
  'Karachi'],
 'Pretoria': ['Santiago', 'Florence', 'Milan', 'Isfahan', 'Zurich'],
 'Madrid': ['Montevideo',
  'Islamabad',
  'Budapest',
  'Mashhad',
  'Tabriz',
  'Chengdu',
  'Arequipa',
  'Hamburg',
  'Alexandria'],
 'Moscow': ['Hanoi', 'Paris', 'Zagreb', "Xi'an"],
 'Berlin': ['Warsaw',
  'Budapest',
  'Florence',
  'Vladivostok',
  'Chicago',
  'Mashhad',
  'Lahore',
  'Aswan'],
 'Bangkok': ['Washington D.C.', 'Jerusalem', 'Bern', 'Medellin'],
 'Stockholm': ['Lisbon', 'Seoul', 'Cancun', 'Vladivostok', 'Tabriz'],
 'Cairo': ['Brasilia',
  'Oslo',
  'Amsterdam',
  'Vienna',
  'Zagreb',
  "Xi'an",
  'Cali',
  'Aswan'],
 'Wellington': ['Canberra', 'New Delhi', "Xi'an", 'Antalya', 'Queenstown'],
 'Ankara': ['Brasilia',
  'Buenos Aires',
  'Dublin',
  'Singapore',
  'Dhaka',
  'Incheon'],
 'Buenos Aires': ['Ankara', 'Manila', 'Brussels', 'Karachi'],
 'Kathmandu': ['Lisbon',
  'Paris',
  'London',
  'Bern',
  'Los Angeles',
  'Lahore',
  'Munich',
  'Christchurch'],
 'Athens': ['New Delhi', 'Islamabad', 'Budapest'],
 'Nairobi': ['Warsaw', 'Bern', 'Milan', 'Marina Bay', 'Izmir'],
 'Lisbon': ['Rome', 'Stockholm', 'Kathmandu', 'Tabriz'],
 'Oslo': ['Cairo',
  'Helsinki',
  'Prague',
  'Vienna',
  'Los Angeles',
  'Shanghai',
  'Troms√∏'],
 'Jakarta': ['Kuala Lumpur', 'Amsterdam', 'Milan', 'Chengdu', 'Troms√∏'],
 'Hanoi': ['Moscow', 'Jerusalem', 'Tehran', 'Cusco', 'Queenstown'],
 'Dublin': ['Ottawa', 'Ankara', 'Bogota', 'Tabriz', 'Incheon'],
 'Beijing': ['Brasilia',
  'Jerusalem',
  'Tehran',
  'Chicago',
  'Shanghai',
  'Marina Bay',
  'Frankfurt'],
 'Paris': ['Moscow', 'Kathmandu', 'Helsinki', 'Lahore'],
 'Santiago': ['New Delhi', 'Pretoria', 'Kyiv', 'Bergen', 'Medellin'],
 'Rabat': ['Canberra', 'Budapest', 'Miami', 'Bursa'],
 'Singapore': ['New Delhi',
  'Ankara',
  'Guangzhou',
  'Hamburg',
  'Alexandria',
  'Aswan'],
 'Lima': ['Copenhagen', 'Colombo', 'Milan', 'Shiraz', 'Isfahan'],
 'Helsinki': ['Oslo',
  'Paris',
  'Prague',
  'Manila',
  'Seoul',
  'Mashhad',
  'Munich',
  'Frankfurt'],
 'Prague': ['Oslo', 'Helsinki', 'Seoul', 'Shanghai', 'Queenstown'],
 'Manila': ['Buenos Aires', 'Helsinki', 'Kyiv', 'Munich', 'Alexandria'],
 'Brussels': ['Buenos Aires', 'Warsaw', 'Islamabad', 'Zurich', 'Munich'],
 'Kuala Lumpur': ['Jakarta',
  'Bern',
  'Vladivostok',
  'Yazd',
  'Troms√∏',
  'Munich',
  'Frankfurt',
  'Christchurch'],
 'Amsterdam': ['Ottawa',
  'Cairo',
  'Jakarta',
  'Lahore',
  'Zurich',
  'Christchurch'],
 'Washington D.C.': ['Rome',
  'Canberra',
  'Bangkok',
  'Jerusalem',
  'Venice',
  'Shiraz',
  'Medellin',
  'Alexandria',
  'Christchurch'],
 'London': ['Rome',
  'Kathmandu',
  'Dhaka',
  'Milan',
  'Miami',
  'Lahore',
  'Frankfurt',
  'Christchurch'],
 'Seoul': ['Stockholm',
  'Helsinki',
  'Prague',
  'Dhaka',
  'Milan',
  'Antalya',
  'Bursa'],
 'Bogota': ['Tokyo',
  'Dublin',
  'Dhaka',
  'Cancun',
  'Incheon',
  'Geneva',
  'Antalya'],
 'Warsaw': ['Berlin',
  'Nairobi',
  'Brussels',
  'Bratislava',
  'Cancun',
  'Chicago',
  'Marseille'],
 'Jerusalem': ['Bangkok',
  'Hanoi',
  'Beijing',
  'Washington D.C.',
  'Montevideo',
  'Shiraz',
  'Arequipa',
  'Zurich',
  'Antalya'],
 'Kyiv': ['Santiago',
  'Manila',
  'Islamabad',
  'Venice',
  'Marseille',
  'Arequipa',
  'Hamburg'],
 'Vienna': ['Cairo',
  'Oslo',
  'Dhaka',
  'Bratislava',
  'Venice',
  'Vladivostok',
  "Xi'an",
  'Geneva',
  'Luxor'],
 'Copenhagen': ['Lima', 'Bern', 'Chicago'],
 'Dhaka': ['Ankara', 'London', 'Seoul', 'Bogota', 'Vienna', 'Los Angeles'],
 'Montevideo': ['Canberra', 'Madrid', 'Jerusalem', 'Bergen'],
 'Bern': ['Bangkok',
  'Kathmandu',
  'Nairobi',
  'Kuala Lumpur',
  'Copenhagen',
  'Islamabad'],
 'Islamabad': ['Madrid',
  'Athens',
  'Brussels',
  'Kyiv',
  'Bern',
  'Venice',
  'Florence',
  'Rotorua'],
 'Budapest': ['Madrid', 'Berlin', 'Athens', 'Rabat', 'Sentosa', 'Marina Bay'],
 'Zagreb': ['Ottawa', 'Moscow', 'Cairo', 'Bratislava', "Xi'an", 'Lyon'],
 'Colombo': ['Lima', 'Geneva', 'Aswan'],
 'Tehran': ['Hanoi', 'Beijing', 'Cancun', 'Medellin', 'Luxor'],
 'Bratislava': ['Warsaw',
  'Vienna',
  'Zagreb',
  'Tabriz',
  'Karachi',
  'Zurich',
  'Izmir'],
 'Cancun': ['Stockholm',
  'Bogota',
  'Warsaw',
  'Tehran',
  'Shiraz',
  'Yazd',
  'Lyon',
  'Zurich',
  'Bursa'],
 'Venice': ['Washington D.C.',
  'Kyiv',
  'Vienna',
  'Islamabad',
  'Marseille',
  'Incheon',
  'Luxor'],
 'Florence': ['Canberra', 'Pretoria', 'Berlin', 'Islamabad', 'Mashhad'],
 'Milan': ['Mexico City',
  'Pretoria',
  'Nairobi',
  'Jakarta',
  'Lima',
  'London',
  'Seoul',
  'Karachi',
  'Queenstown'],
 'Saint Petersburg': ['Shanghai', 'Bergen', 'Medellin', 'Luxor'],
 'Vladivostok': ['Berlin', 'Stockholm', 'Kuala Lumpur', 'Vienna', 'Chicago'],
 'New York City': ['Mexico City', 'Chicago', 'Marseille', 'Geneva', 'Rotorua'],
 'Los Angeles': ['Canberra', 'Kathmandu', 'Oslo', 'Dhaka', "Xi'an"],
 'Chicago': ['Rome',
  'Berlin',
  'Beijing',
  'Warsaw',
  'Copenhagen',
  'Vladivostok',
  'New York City',
  'Marina Bay'],
 'Miami': ['Tokyo', 'Rabat', 'London', 'Lyon', 'Rotorua'],
 'Shiraz': ['Mexico City',
  'Lima',
  'Washington D.C.',
  'Jerusalem',
  'Cancun',
  'Luxor'],
 'Isfahan': ['New Delhi', 'Pretoria', 'Lima', 'Bergen', 'Medellin'],
 'Mashhad': ['Madrid', 'Berlin', 'Helsinki', 'Florence', 'Troms√∏', 'Sentosa'],
 'Tabriz': ['Madrid',
  'Stockholm',
  'Lisbon',
  'Dublin',
  'Bratislava',
  'Rotorua'],
 'Yazd': ['Rome',
  'Kuala Lumpur',
  'Cancun',
  'Marseille',
  'Cusco',
  'Busan',
  'Frankfurt',
  'Alexandria'],
 'Shanghai': ['Canberra',
  'Oslo',
  'Beijing',
  'Prague',
  'Saint Petersburg',
  'Karachi'],
 'Guangzhou': ['Singapore', 'Busan', 'Frankfurt', 'Alexandria'],
 'Chengdu': ['Mexico City',
  'Canberra',
  'Madrid',
  'Jakarta',
  'Troms√∏',
  'Busan'],
 "Xi'an": ['Moscow',
  'Cairo',
  'Wellington',
  'Vienna',
  'Zagreb',
  'Los Angeles',
  'Lyon',
  'Queenstown'],
 'Bergen': ['Mexico City',
  'Santiago',
  'Montevideo',
  'Saint Petersburg',
  'Isfahan'],
 'Troms√∏': ['New Delhi',
  'Oslo',
  'Jakarta',
  'Kuala Lumpur',
  'Mashhad',
  'Chengdu'],
 'Marseille': ['Warsaw', 'Kyiv', 'Venice', 'New York City', 'Yazd', 'Lyon'],
 'Lyon': ['Zagreb', 'Cancun', 'Miami', "Xi'an", 'Marseille', 'Sentosa'],
 'Sentosa': ['Budapest', 'Mashhad', 'Lyon', 'Rotorua'],
 'Marina Bay': ['Nairobi',
  'Beijing',
  'Budapest',
  'Chicago',
  'Izmir',
  'Rotorua'],
 'Cusco': ['Hanoi', 'Yazd', 'Cali', 'Christchurch'],
 'Arequipa': ['Madrid',
  'Jerusalem',
  'Kyiv',
  'Medellin',
  'Geneva',
  'Christchurch'],
 'Busan': ['Yazd', 'Guangzhou', 'Chengdu', 'Christchurch'],
 'Incheon': ['Ankara', 'Dublin', 'Bogota', 'Venice', 'Munich'],
 'Medellin': ['Bangkok',
  'Santiago',
  'Washington D.C.',
  'Tehran',
  'Saint Petersburg',
  'Isfahan',
  'Arequipa'],
 'Cali': ['Cairo', 'Cusco', 'Geneva'],
 'Lahore': ['Tokyo',
  'Mexico City',
  'Berlin',
  'Kathmandu',
  'Paris',
  'Amsterdam',
  'London',
  'Rotorua'],
 'Karachi': ['Canberra',
  'New Delhi',
  'Buenos Aires',
  'Bratislava',
  'Milan',
  'Shanghai',
  'Geneva'],
 'Zurich': ['Pretoria',
  'Brussels',
  'Amsterdam',
  'Jerusalem',
  'Bratislava',
  'Cancun',
  'Hamburg'],
 'Geneva': ['Bogota',
  'Vienna',
  'Colombo',
  'New York City',
  'Arequipa',
  'Cali',
  'Karachi'],
 'Izmir': ['Brasilia',
  'Nairobi',
  'Bratislava',
  'Marina Bay',
  'Hamburg',
  'Aswan'],
 'Antalya': ['Wellington', 'Seoul', 'Bogota', 'Jerusalem'],
 'Bursa': ['Ottawa', 'Rabat', 'Seoul', 'Cancun'],
 'Munich': ['Ottawa',
  'Kathmandu',
  'Helsinki',
  'Manila',
  'Brussels',
  'Kuala Lumpur',
  'Incheon'],
 'Hamburg': ['Madrid', 'Singapore', 'Kyiv', 'Zurich', 'Izmir'],
 'Frankfurt': ['Beijing',
  'Helsinki',
  'Kuala Lumpur',
  'London',
  'Yazd',
  'Guangzhou'],
 'Alexandria': ['Madrid',
  'Singapore',
  'Manila',
  'Washington D.C.',
  'Yazd',
  'Guangzhou'],
 'Luxor': ['Canberra',
  'Vienna',
  'Tehran',
  'Venice',
  'Saint Petersburg',
  'Shiraz'],
 'Aswan': ['Berlin', 'Cairo', 'Singapore', 'Colombo', 'Izmir', 'Rotorua'],
 'Christchurch': ['Kathmandu',
  'Kuala Lumpur',
  'Amsterdam',
  'Washington D.C.',
  'London',
  'Cusco',
  'Arequipa',
  'Busan'],
 'Queenstown': ['Wellington', 'Hanoi', 'Prague', 'Milan', "Xi'an"],
 'Rotorua': ['Islamabad',
  'New York City',
  'Miami',
  'Tabriz',
  'Sentosa',
  'Marina Bay',
  'Lahore',
  'Aswan']}

In [176]:
def second_connection_city(connections_dict):
    second_connections_dict = {}
    for key, value in connections_dict.items():
        second_connections_dict[key] = {}
        for i in range(len(value)):
            second_neighbors = connections_dict[connections_dict[key][i]]
            result = [s for s in second_neighbors if s not in value]
            result.remove(key)
                
            second_connections_dict[key][connections_dict[key][i]] = result


    return second_connections_dict

In [177]:
second_connections_dict = second_connection_city(connections_dict)

In [186]:
print(second_connections_dict.get('Canberra'))

{'Wellington': ['New Delhi', "Xi'an", 'Antalya', 'Queenstown'], 'Rabat': ['Budapest', 'Miami', 'Bursa'], 'Washington D.C.': ['Rome', 'Bangkok', 'Jerusalem', 'Venice', 'Shiraz', 'Medellin', 'Alexandria', 'Christchurch'], 'Montevideo': ['Madrid', 'Jerusalem', 'Bergen'], 'Florence': ['Pretoria', 'Berlin', 'Islamabad', 'Mashhad'], 'Los Angeles': ['Kathmandu', 'Oslo', 'Dhaka', "Xi'an"], 'Shanghai': ['Oslo', 'Beijing', 'Prague', 'Saint Petersburg'], 'Chengdu': ['Mexico City', 'Madrid', 'Jakarta', 'Troms√∏', 'Busan'], 'Karachi': ['New Delhi', 'Buenos Aires', 'Bratislava', 'Milan', 'Geneva'], 'Luxor': ['Vienna', 'Tehran', 'Venice', 'Saint Petersburg', 'Shiraz']}

In [183]:
init_graph = {}
for node in nodes:
    init_graph[node] = {}

for i in source_airport_dict:
    init_graph[source_airport_dict[i]][destination_airport_dict[i]] = parameter[i]

NameError: name 'nodes' is not defined